// Code generated by MockGen. DO NOT EDIT.
// Source: yotube_resolver.go

// Package yotube_resolver is a generated GoMock package.
package yotube_resolver

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	video "github.com/nds-masashi/sr/domain/model/video"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetVideoUrl mocks base method.
func (m *MockService) GetVideoUrl(title string, limit int) ([]video.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoUrl", title, limit)
	ret0, _ := ret[0].([]video.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoUrl indicates an expected call of GetVideoUrl.
func (mr *MockServiceMockRecorder) GetVideoUrl(title, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoUrl", reflect.TypeOf((*MockService)(nil).GetVideoUrl), title, limit)
}
